# Generated by Django 3.2.13 on 2023-10-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('fabricante', models.CharField(max_length=70)),
                ('automatico_manual', models.CharField(max_length=20)),
                ('data_fabricação', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='videogames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('empresa', models.CharField(max_length=50)),
                ('estilo', models.CharField(max_length=50)),
                ('data_lançamento', models.DateField()),
            ],
        ),
    ]
